apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "hello-akka.full_name" . }}
  labels:
    {{- include "hello-akka.release_labels" . | indent 4 }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        {{- include "hello-akka.release_labels" . | indent 8 }}
    spec:
      containers:
        - name: hello-akka
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
          - containerPort: 8080
            protocol: TCP
          env:
          - name: SERVER_HOST
            value: {{ .Values.env.host }}
          - name: SERVER_PORT
            value: {{ .Values.env.port }}
          - name: xmx
            value: {{ .Values.env.xmx }}
          - name: xms
            value: {{ .Values.env.xms }}