apiVersion: v1
kind: Service
metadata:
  name: {{ template "hello-akka.full_name" . }}
  labels:
    {{- include "hello-akka.release_labels" . | indent 4 }}
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: {{ template "hello-akka.full_name" . }}
